-- Enterprise Copilot schema. Portable ANSI SQL – runs on H2 (demo) and PostgreSQL (compose).

CREATE TABLE pipelines (
                           id                 UUID PRIMARY KEY,
                           ticket_key         VARCHAR(64)  NOT NULL,
                           title              VARCHAR(512) NOT NULL,
                           description        TEXT,
                           source             VARCHAR(32)  NOT NULL,
                           scenario           VARCHAR(64)  NOT NULL,
                           ai_mode            VARCHAR(16)  NOT NULL,
                           state              VARCHAR(48)  NOT NULL,
                           approval_state     VARCHAR(24)  NOT NULL,
                           analysis_json      TEXT,
                           code_json          TEXT,
                           review_json        TEXT,
                           deployment_json    TEXT,
                           created_at         TIMESTAMP    NOT NULL,
                           updated_at         TIMESTAMP    NOT NULL
);

CREATE INDEX idx_pipelines_created_at ON pipelines (created_at);

-- Append-only audit trail. Never updated or deleted.

CREATE TABLE audit_events (
                              id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              pipeline_id        UUID         NOT NULL,
                              agent              VARCHAR(64)  NOT NULL,
                              action             VARCHAR(64)  NOT NULL,
                              decision           VARCHAR(64),
                              policy_outcome     VARCHAR(64),
                              detail             TEXT,
                              created_at         TIMESTAMP    NOT NULL
);

CREATE INDEX idx_audit_pipeline ON audit_events (pipeline_id, created_at);